apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster-capella
spec:
  description: Capella postgresql cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:14.7
  instances: {{ required "postgresql database replicas required" .Values.pgInstances  }}
  startDelay: 45
  stopDelay: 150
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: pgcluster-capella-app-user
  storage:
    size: 10Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
      volumeMode: Filesystem
