apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster-capella
spec:
  description: Capella postgresql cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:14.7
  instances: {{ required "postgresql database replicas required" .Values.pgInstances  }}
  startDelay: 45
  stopDelay: 150
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      shared_buffers: 256MB
      max_connections: '500'
      synchronous_commit: "off"
      update_process_title: "off"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      auto_explain.log_min_duration: 10s
    pg_hba:
      - host all all 10.244.0.0/16 md5
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: pgcluster-capella-app-user
  storage:
    size: 10Gi
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    nodeSelector:
      node.kubernetes.io/instance-type: {{ required "manager node affinity instance-type required" .Values.managerInstanceType | quote }}
