---
apiVersion: v1
data:
  password: {{ .Values.secrets.pgClusterPassword | b64enc  }}
  username: {{ .Values.secrets.pgClusterUsername | b64enc  }}
kind: Secret
metadata:
  name: pgcluster-capella-app-user
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: capella-ftc-license
type: Opaque
data:
  mode: {{ .Values.secrets.ftcLicenseMode | b64enc  }}
  key: {{ .Values.secrets.ftcLicenseKey | b64enc  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: capella-cambriacluster-api
type: Opaque
data:
  token: {{ .Values.secrets.cambriaClusterAPIToken | b64enc  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: capella-webui
type: Opaque
data:
  userstring: {{ .Values.secrets.cambriaClusterWebUIUser | b64enc  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api
type: Opaque
data:
  token: {{ .Values.secrets.linodeAPIToken | b64enc  }}

